import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Bungee } from "next/font/google";
import Link from "next/link";
import Shop from "./Shop/page";
import { HiHome } from "react-icons/hi";
import { HiTrendingUp } from "react-icons/hi";
import Image from "next/image";

// Import Bungee with weight 400
const bungee = Bungee({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bungee", // optional CSS variable
});
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={bungee.className}>
      <body>
        <header className="fixed w-full z-10 flex justify-between items-center bg-white/20 border border-black/20 backdrop-blur-md p-3 rounded-xl">
          <div>
            <Image
            src='/Logo.png'
            height={50}
            width={50}
            alt="logo"
            className="rounded-3xl"

            />
          </div>

          {/* categories/trending  */}
          <div className="hidden md:flex relative space-x-6 ">
           <Link href='/'><HiHome className="text-xl"/></Link>
            {/* Trending */}
            <Link href="/trending" className="flex gap-1  ">
            <HiTrendingUp className="text-black/60"/>Trending</Link>

            {/* Categories wrapper (ONLY this has group) */}
            <div className="relative group">
              <Link href="#" className="text-black cursor-pointer flex gap-1">
          
                Categories ▼
              </Link>

              {/* Dropdown menu */}
              <div
                className="absolute top-full left-0 mt-2 w-40 bg-white border border-gray-200 rounded-md shadow-lg
               opacity-0 invisible group-hover:opacity-100 group-hover:visible
               transition-all duration-200 z-20"
              >
                <Link
                  href="/categories/fashion" // Correct link path
                  className="block px-4 py-2 hover:text-white hover:bg-[#666666] rounded-lg"
                >
                  Fashion
                </Link>

                <Link
                  href="/categories/beauty" // Correct link path
                  className="block px-4 py-2 hover:text-white hover:bg-[#666666] rounded-lg"
                >
                  Beauty
                </Link>

                <Link
                  href="/categories/tech" // Correct link path
                  className="block px-4 py-2 hover:text-white hover:bg-[#666666] rounded-lg"
                >
                  Tech
                </Link>
              </div>
            </div>
          </div>
           
          <div>
             <Shop/>
                <div className="relative group hidden md:flex">
              <Link href="#" className="text-black cursor-pointer">
                Shop ▼
              </Link>

              {/* Dropdown menu */}
              <div
                className="absolute top-full right-0 mt-2 w-40 bg-white border border-gray-200 rounded-md shadow-lg
               opacity-0 invisible group-hover:opacity-100 group-hover:visible
               transition-all duration-200 z-20"
              >
                <Link href='/trending' className="block px-4 py-2 hover:text-white hover:bg-[#666666] rounded-lg">
                Trending
                </Link>
                <Link
                  href="/categories/fashion" // Correct link path
                  className="block px-4 py-2 hover:text-white hover:bg-[#666666] rounded-lg"
                >
                  Fashion
                </Link>

                <Link
                  href="/categories/beauty" // Correct link path
                  className="block px-4 py-2 hover:text-white hover:bg-[#666666] rounded-lg"
                >
                  Beauty
                </Link>

                <Link
                  href="/categories/tech" // Correct link path
                  className="block px-4 py-2 hover:text-white hover:bg-[#666666] rounded-lg"
                >
                  Tech
                </Link>
              </div>
            </div>
          
          </div>

        </header>

        {children}
        <footer className="no-bungee text-xl text-black border border-black/20 p-3 rounded-xl ">
         <h1>
           © 2026 Luxeallus Web Portal. All rights reserved.
         </h1>
          <h2>
            Under Development
          </h2>
          <h3>
            This Page Conatains Affilaite links.No Extra Cost To You
          </h3>
          
        </footer>
      </body>
    </html>
  );
}
